// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTb-ADECijUix0LS_LqsdKHezQUtnWeDU',
    appId: '1:482406091527:web:5e5ed1765619658e7a53a2',
    messagingSenderId: '482406091527',
    projectId: 'sejenak-b9227',
    authDomain: 'sejenak-b9227.firebaseapp.com',
    storageBucket: 'sejenak-b9227.firebasestorage.app',
    measurementId: 'G-5ZTDMX84XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp30iVtCJottuDdWyTgDKsmYsxahPlXa0',
    appId: '1:550689254127:android:dff6a5a6e4858d713ec91a',
    messagingSenderId: '550689254127',
    projectId: 'sejenak-7bf82',
    storageBucket: 'sejenak-7bf82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWMOywf7I8bGuyGq3tayfQxLVlBNOOY0',
    appId: '1:482406091527:ios:cd33edeebe4246d37a53a2',
    messagingSenderId: '482406091527',
    projectId: 'sejenak-b9227',
    storageBucket: 'sejenak-b9227.firebasestorage.app',
    androidClientId: '482406091527-o1db4384l0c2oba9vc36p0p0i3altmtf.apps.googleusercontent.com',
    iosClientId: '482406091527-ob97j9vctf9dn0vtmgu6akvrmcmrbgpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sejenak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWMOywf7I8bGuyGq3tayfQxLVlBNOOY0',
    appId: '1:482406091527:ios:cd33edeebe4246d37a53a2',
    messagingSenderId: '482406091527',
    projectId: 'sejenak-b9227',
    storageBucket: 'sejenak-b9227.firebasestorage.app',
    androidClientId: '482406091527-o1db4384l0c2oba9vc36p0p0i3altmtf.apps.googleusercontent.com',
    iosClientId: '482406091527-ob97j9vctf9dn0vtmgu6akvrmcmrbgpt.apps.googleusercontent.com',
    iosBundleId: 'com.example.sejenak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTb-ADECijUix0LS_LqsdKHezQUtnWeDU',
    appId: '1:482406091527:web:008ce54b637492497a53a2',
    messagingSenderId: '482406091527',
    projectId: 'sejenak-b9227',
    authDomain: 'sejenak-b9227.firebaseapp.com',
    storageBucket: 'sejenak-b9227.firebasestorage.app',
    measurementId: 'G-FT7Q8LLWV9',
  );
}